ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
