ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/sensor/cci
obj-$(CONFIG_MSMB_CAMERA_NOUGAT)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
