ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/sensor/io
obj-$(CONFIG_MSM_CSIPHY) += msm_csiphy.o
