ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/sensor/io
obj-$(CONFIG_MSMB_CAMERA_NOUGAT) += msm_flash.o
