--- drivers/staging/Makefile
+++ drivers/staging/Makefile
@@ -45,3 +45,6 @@ obj-$(CONFIG_MTD_SPINAND_MT29F)	+= mt29f_spinand/
 obj-$(CONFIG_GS_FPGABOOT)	+= gs_fpgaboot/
 obj-$(CONFIG_CRYPTO_SKEIN)	+= skein/
 obj-$(CONFIG_UNISYSSPAR)	+= unisys/
+obj-$(CONFIG_PRIMA_WLAN)        += prima/
+obj-$(CONFIG_PRONTO_WLAN)       += prima/
+
