ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
