ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-nougat/sensor/cci
obj-$(CONFIG_MSMB_CAMERA_NOUGAT) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/ ir_led/ ir_cut/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
